# Site settings
title: elily漫评

# Handling Reading
exclude:
  - README.md

keep_files:
  - assets

# Conversion
markdown: kramdown

# Outputting
permalink: /post/:year/:title.html
timezone: Asia/Hong_Kong
